// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IOStrategy is an autogenerated mock type for the IOStrategy type
type IOStrategy struct {
	mock.Mock
}

// Write provides a mock function with given fields: matrix, output
func (_m *IOStrategy) Write(matrix [][]string, output string) error {
	ret := _m.Called(matrix, output)

	var r0 error
	if rf, ok := ret.Get(0).(func([][]string, string) error); ok {
		r0 = rf(matrix, output)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
